Integrate massive search
sulu/SuluContentBundle pull request #166
Opened 2020-08-19 13:42 UTC by luca-rath

2020-08-25 09:00 UTC, wachterjohannes requested changes
Smaller changes

2020-08-25 09:00 UTC, wachterjohannes commented on Content/Infrastructure/Sulu/Search/ContentSearchMetadataProvider.php
> +        $classMetadata = $this->entityManager->getClassMetadata($this->contentRichEntityClass);
would extract it // cc @alexander-schranz trait?

2020-08-25 09:04 UTC, alexander-schranz commented on Content/Infrastructure/Sulu/Search/ContentReindexProvider.php
> +        $classMetadata = $this->entityManager->getClassMetadata($this->contentRichEntityClass);
We have some thoughts about getting rid of it. Would create an issue so we will have a look at it after the dimension refractoring. At current state its okay for me having thins logic here.

2020-08-25 09:05 UTC, alexander-schranz commented on Content/Application/ContentWorkflow/Subscriber/PublishTransitionSubscriber.php
> +        $eventName = 'workflow.content_workflow.transition.' . WorkflowInterface::WORKFLOW_TRANSITION_PUBLISH;
👍

2020-08-25 09:06 UTC, luca-rath commented on Content/Infrastructure/Sulu/Search/ContentSearchMetadataProvider.php
> +        $classMetadata = $this->entityManager->getClassMetadata($this->contentRichEntityClass);
@wachterjohannes @alexander-schranz What about adding a static method `ContentRichEntityInterface::getDimensionContentClass()`? That would be a lot easier to use than a trait

2020-08-25 09:09 UTC, alexander-schranz commented on Content/Application/ContentIndexer/ContentIndexerInterface.php
> +    public function delete(string $resourceKey, $id): void;
This is also a `deindex` function or? What about `deindexResource` /cc @wachterjohannes

2020-08-25 09:13 UTC, alexander-schranz commented on Content/Infrastructure/Sulu/Search/ContentSearchMetadataProvider.php
> +    protected function getMetadata(string $className, StructureMetadata $structureMetadata): ClassMetadata
At current state I would make this private. Don't want to add a extension point at current state here. /cc @wachterjohannes what do you think?

2020-08-25 09:16 UTC, alexander-schranz commented on Content/Infrastructure/Sulu/Search/ContentSearchMetadataProvider.php
> +        $classMetadata = $this->entityManager->getClassMetadata($this->contentRichEntityClass);
No this should come from the doctrine metadata and the developer should not get into contact about it. And it will change in the future. A `@internal` trait is okay for me at current state, keeping it like this is also okay.

2020-08-25 09:46 UTC, wachterjohannes commented on Content/Infrastructure/Sulu/Search/ContentSearchMetadataProvider.php
> +    protected function getMetadata(string $className, StructureMetadata $structureMetadata): ClassMetadata
👍

2020-08-25 09:46 UTC, wachterjohannes commented on Content/Application/ContentIndexer/ContentIndexerInterface.php
> +    public function delete(string $resourceKey, $id): void;
👍

2020-08-25 13:45 UTC, luca-rath commented on Content/Application/ContentIndexer/ContentIndexer.php
> +    public function deindex(string $resourceKey, $id, array $dimensionAttributes = []): void
@wachterjohannes @alexander-schranz what do you think, if the default deindex method will use a search query to find documents that need to be deindexed? That beautifies the public interface a lot IMO

2020-08-25 14:01 UTC, wachterjohannes commented on Content/Application/ContentIndexer/ContentIndexer.php
> +    public function deindex(string $resourceKey, $id, array $dimensionAttributes = []): void
@sulu-io-user if you talk about the name - i love it 😂

2020-08-25 14:28 UTC, luca-rath commented on Content/Application/ContentIndexer/ContentIndexer.php
> +    public function deindex(string $resourceKey, $id, array $dimensionAttributes = []): void
Especially i was talking about removing the `deindex()` method which took `$contentRichEntity` and `$dimensionAttributes` as arguments and replacing it with this `deindex()` method

2020-08-26 13:12 UTC, wachterjohannes commented on Content/Application/ContentIndexer/ContentIndexer.php
> +    public function deindex(string $resourceKey, $id, array $dimensionAttributes = []): void
👍

2020-08-26 13:13 UTC, wachterjohannes approved these changes

2020-08-26 13:22 UTC, alexander-schranz approved these changes

2020-08-26 13:23 UTC, merged