Feature/resource mapping
sulu/SuluContentBundle pull request #168
Opened 2020-09-16 15:04 UTC by mgwestwerk

#167

2020-10-05 10:07 UTC, nnatter reviewed
looks good to me otherwise 🙂  /cc @alexander-schranz

2020-10-05 10:07 UTC, nnatter commented on Content/Application/ContentMetadataInspector/ContentMetadataInspectorInterface.php
> +    public function getDimensionContentMappingProperty(string $contentRichEntityClass): string;
think i would call this `getDimensionContentPropertyName`

2020-10-05 10:07 UTC, nnatter commented on Tests/Unit/Content/Application/ContentMetadataInspector/ContentMetadataInspectorTest.php
> +    public function testGetDimensionContentClass(): void
test case for the second method is missing

2020-10-05 10:07 UTC, nnatter commented
thanks for working on this! @mgwestwerk

2020-10-05 11:54 UTC, alexander-schranz requested changes
@mgwestwerk Thank you for working for this. Some small change requests and some things to discuss.

2020-10-05 11:54 UTC, alexander-schranz commented on Content/Application/ContentMetadataInspector/ContentMetadataInspector.php
> +class ContentMetadataInspector implements ContentMetadataInspectorInterface
```suggestion

/**
 * @internal This class is for internal use and we can not given any bc promise for this as it can change.
 */
class ContentMetadataInspector implements ContentMetadataInspectorInterface
```

2020-10-05 11:54 UTC, alexander-schranz commented on Content/Application/ContentMetadataInspector/ContentMetadataInspectorInterface.php
> +interface ContentMetadataInspectorInterface
```suggestion

/**
 * @internal This interface is for internal use and we can not given any bc promise for this as it can change.
 */
interface ContentMetadataInspectorInterface
```

2020-10-05 11:54 UTC, alexander-schranz commented on Content/Application/ContentMetadataInspector/ContentMetadataInspectorInterface.php
> +    public function getDimensionContentMappingProperty(string $contentRichEntityClass): string;
agree we should be as specific as possible

2020-10-05 11:54 UTC, alexander-schranz commented on Resources/config/services.xml
> +        <service id="Sulu\Bundle\ContentBundle\Content\Application\ContentMetadataInspector\ContentMetadataInspectorInterface" alias="sulu_content.content_metadata_inspector"/>
I would not make this service autowireable so this should not exist.

2020-10-05 11:54 UTC, alexander-schranz commented on Resources/config/services.xml
> +        <service id="sulu_content.content_metadata_inspector" class="Sulu\Bundle\ContentBundle\Content\Application\ContentMetadataInspector\ContentMetadataInspector">
I'm not sure if I would make a service for it as its internal logic, I would make construct it where needed in the `__construct` function of that service.

@nnatter what do you think?

2020-10-05 12:04 UTC, nnatter commented on Resources/config/services.xml
> +        <service id="sulu_content.content_metadata_inspector" class="Sulu\Bundle\ContentBundle\Content\Application\ContentMetadataInspector\ContentMetadataInspector">
that way it is not possible to overwrite the service

2020-10-05 12:09 UTC, mgwestwerk commented on Resources/config/services.xml
> +        <service id="sulu_content.content_metadata_inspector" class="Sulu\Bundle\ContentBundle\Content\Application\ContentMetadataInspector\ContentMetadataInspector">
To give you my reasoning, why i made it a service: My problem that i described in #168 requires me to override the default functionality that maps the `ContentRichEntity` class to the `DimensionContent` class. By putting it into a service I was able to decorate it and achieve this goal.

2020-10-09 11:15 UTC, alexander-schranz commented
I created an issue for it (#170). At current state its okay for me but hope we get ride of it soon and detect the target classes correctly then.

2020-10-09 11:16 UTC, merged