Pass DimensionContentCollection to DataMapper services
sulu/SuluContentBundle pull request #182
Opened 2021-01-18 13:48 UTC by nnatter

2021-01-18 17:30 UTC, alexander-schranz requested changes
I personally not so happy with the Preview Handling, but it was also not good before. I would atleast simulate the count: 2 and mark the PreviewCollection as internal so we can change it the way we need it in future.

2021-01-18 17:30 UTC, alexander-schranz commented on Content/Infrastructure/Sulu/Preview/PreviewDimensionContentCollection.php
> +class PreviewDimensionContentCollection implements \IteratorAggregate, DimensionContentCollectionInterface
Not sure about this class. Can we mark it as `@internal` at current state.

2021-01-18 17:30 UTC, alexander-schranz commented on Content/Infrastructure/Sulu/Preview/PreviewDimensionContentCollection.php
> +        return ['locale' => $this->previewLocale];
A DimensionCollection should always return all its `DimensionAttributes` so we should ˚/array_merge()` them here with the `getDefaultDimensionAttributes`.

2021-01-18 17:30 UTC, alexander-schranz commented on Content/Infrastructure/Sulu/Preview/PreviewDimensionContentCollection.php
> +    }
Not really happy with this :(

2021-01-18 17:30 UTC, alexander-schranz commented on Content/Infrastructure/Sulu/Preview/PreviewDimensionContentCollection.php
> +    }
Not sure if we should return here `2` to simulate that we have a unlocalized and localizedObject.

2021-01-18 17:50 UTC, nnatter commented
@alexander-schranz Not really happy about the preview handling too, but I dont have a better idea at the moment. Do you see a better alternative?

2021-01-19 08:30 UTC, nnatter commented on Content/Infrastructure/Sulu/Preview/PreviewDimensionContentCollection.php
> +class PreviewDimensionContentCollection implements \IteratorAggregate, DimensionContentCollectionInterface
👍

2021-01-19 08:30 UTC, nnatter commented on Content/Infrastructure/Sulu/Preview/PreviewDimensionContentCollection.php
> +        return ['locale' => $this->previewLocale];
👍

2021-01-19 08:31 UTC, nnatter commented on Content/Infrastructure/Sulu/Preview/PreviewDimensionContentCollection.php
> +    }
think i would not return 2 because that is misleading

2021-01-19 08:39 UTC, nnatter commented on Content/Application/ContentDataMapper/ContentDataMapperInterface.php
>      public function map(
TODO: document this in the `UPGRADE.md`

2021-01-19 08:39 UTC, nnatter commented on Content/Application/ContentDataMapper/DataMapper/DataMapperInterface.php
>      public function map(
TODO: document this in the `UPGRADE.md`

2021-01-19 08:40 UTC, nnatter commented on Content/Domain/Model/DimensionContentCollection.php
> -    public function getUnlocalizedDimensionContent(): ?DimensionContentInterface
TODO: document this in the `UPGRADE.md`

2021-01-19 08:40 UTC, nnatter commented on Content/Domain/Model/DimensionContentCollectionInterface.php
> -    public function getUnlocalizedDimensionContent(): ?DimensionContentInterface;
TODO: document this in the `UPGRADE.md`

2021-01-19 08:42 UTC, nnatter commented on Content/Infrastructure/Sulu/Preview/PreviewDimensionContentCollection.php
> +    }
i could adjust the `DimensionContentCollectionInterface` to not extend `Countable` as described in https://github.com/sulu/SuluContentBundle/issues/178 to get rid of the method 😇

2021-01-20 15:49 UTC, merged