Add subscriber to delete route when a content-rich entity got removed
sulu/SuluContentBundle pull request #198
Opened 2021-09-28 14:01 UTC by wachterjohannes

2021-09-28 19:03 UTC, alexander-schranz requested changes

2021-09-28 19:03 UTC, alexander-schranz commented on Content/Infrastructure/Doctrine/RouteRemover.php
> +class RouteRemover implements EventSubscriber
This should not be a public service so it should be internal and final:

```suggestion
/**
 * @internal
 * @final
 */
class RouteRemover implements EventSubscriber
```

2021-09-28 19:03 UTC, alexander-schranz commented on Tests/Unit/Content/Infrastructure/Doctrine/RouteRemoverTest.php
> +        $event = $this->prophesize(LifecycleEventArgs::class);
would not mock the `LifecycleEventArgs` we should go with a real event instance:

```
$event = new LifecycleEventArgs($object, $entityManager->reveal());
```

2021-09-29 06:10 UTC, wachterjohannes commented on Content/Infrastructure/Doctrine/RouteRemover.php
> +class RouteRemover implements EventSubscriber
done

2021-09-29 06:10 UTC, wachterjohannes commented on Tests/Unit/Content/Infrastructure/Doctrine/RouteRemoverTest.php
> +        $event = $this->prophesize(LifecycleEventArgs::class);
done

2021-09-29 07:01 UTC, nnatter commented on Content/Infrastructure/Doctrine/RouteRemover.php
> +        $entityClass = ClassUtils::getRealClass(\get_class($object));
why do we need `ClassUtils::getRealClass` here? 🤔 
i think we should determine the class based on the resource key like we do in the `RoutableDataMapper`:
https://github.com/sulu/SuluContentBundle/blob/bd6674a20de5737a35a3fdfab373a1e495cf75ac/Content/Application/ContentDataMapper/DataMapper/RoutableDataMapper.php#L140-L147

2021-09-29 07:05 UTC, nnatter commented on Content/Infrastructure/Doctrine/RouteRemover.php
> +        if (!$object instanceof ContentRichEntityInterface) {
wouldnt it be more intuitive to do this for `RoutableInterface` entities? i guess you did not do that because they are deleted because of database level cascading, right?

2021-09-29 09:07 UTC, wachterjohannes commented on Content/Infrastructure/Doctrine/RouteRemover.php
> +        if (!$object instanceof ContentRichEntityInterface) {
exactly - they are moved by cascading on database level

2021-09-29 09:10 UTC, wachterjohannes commented on Content/Infrastructure/Doctrine/RouteRemover.php
> +        $entityClass = ClassUtils::getRealClass(\get_class($object));
we would have to load unnecessary data from the database (dimensions) - The `ClassUtils::getRealClass` removes the proxy classes from the return - so we get the correct class

2021-09-29 10:40 UTC, alexander-schranz commented on Content/Infrastructure/Doctrine/RouteRemover.php
> +        $entityClass = ClassUtils::getRealClass(\get_class($object));
The `ContentMetadataInspector` does not load anything.

2021-09-29 12:53 UTC, alexander-schranz commented on Content/Infrastructure/Doctrine/RouteRemover.php
> +        $entityClass = ClassUtils::getRealClass(\get_class($object));
@wachterjohannes still would use the `ContentMetadataInspector` here and then use ClassUtils::getRealClass inside it. But we should use here the routeMappings configuration.

2021-09-29 12:56 UTC, wachterjohannes commented on Content/Infrastructure/Doctrine/RouteRemover.php
> +        $entityClass = ClassUtils::getRealClass(\get_class($object));
@alexander-schranz is there a good reason todo it? it is really don't necessary and i would keep it as slim as possible

2021-09-29 13:00 UTC, alexander-schranz commented on Content/Infrastructure/Doctrine/RouteRemover.php
> +        $entityClass = ClassUtils::getRealClass(\get_class($object));
It should be consistent and the only source of true for the route configuraiton is the routingMapping variable. We had in the past problems when somebody did overwrite entities that it did use get_class and it did then not longer work.

2021-09-29 13:59 UTC, wachterjohannes commented
@alexander-schranz @nnatter fixed

2021-09-30 12:18 UTC, nnatter commented on Tests/Application/ExampleTestBundle/Entity/Example.php
> +    public function setId($id): self
i am afraid that people will blindly copy (and maybe even use) this if we add it to the example.
we only need this for the test - right? i think i would set it via reflection in the test then

2021-09-30 12:18 UTC, alexander-schranz approved these changes

2021-09-30 12:41 UTC, wachterjohannes commented on Tests/Application/ExampleTestBundle/Entity/Example.php
> +    public function setId($id): self
@nnatter done

2021-09-30 13:01 UTC, nnatter approved these changes

2021-09-30 13:01 UTC, merged