Add Webspace select to Settings Tab
sulu/SuluContentBundle pull request #211
Opened 2021-10-13 18:15 UTC by alexander-schranz

Most entities like `Article` and any routable Custom Entity will have a webspace selection in its settings tab. I did go here with the name `WebspaceInterface`.

The entity like `Page` will not implement it as the webspace will there not be on the PageDimensionContent Entity and so not implement for its webspace a content interface. Other entity like snippet which will have content will not have a Webspace field or relation.

## TODO

 - [x] Move additional webspaces to seperate PR: (https://github.com/sulu/SuluContentBundle/pull/213)
 - [x] Add issue for SEO Canonical Handling (https://github.com/sulu/SuluContentBundle/issues/214)

2021-10-15 08:36 UTC, wachterjohannes requested changes

2021-10-15 08:36 UTC, wachterjohannes commented on Resources/config/data-mapper.xml
> +            <tag name="sulu_content.data_mapper" priority="24"/>
why 24? seems a strange number 🙈

2021-10-15 08:36 UTC, wachterjohannes commented on Resources/config/merger.xml
> +            <tag name="sulu_content.merger" priority="24"/>
same here

2021-10-15 08:38 UTC, alexander-schranz commented on Resources/config/merger.xml
> +            <tag name="sulu_content.merger" priority="24"/>
is between the other mergers

2021-10-18 14:32 UTC, alexander-schranz commented on Resources/config/data-mapper.xml
> +            <tag name="sulu_content.data_mapper" priority="24"/>
@wachterjohannes Which steps between the mergers would you use?

2021-10-19 12:26 UTC, wachterjohannes commented on Resources/config/data-mapper.xml
> +            <tag name="sulu_content.data_mapper" priority="24"/>
its ok 😂 thought it is a strange number - maybe add a comment that it has to be between

2021-10-19 12:26 UTC, wachterjohannes approved these changes

2021-10-19 12:35 UTC, merged